golang fixed

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,28 +1,36 @@
-# This workflow will build a golang project
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
-
-name: Go
+name: Go Programs Check
 
 on:
   push:
-    branches: [ "main" ]
+    branches:
+      - main
   pull_request:
-    branches: [ "main" ]
+    branches:
+      - main
 
 jobs:
-
-  build:
+  check:
     runs-on: ubuntu-latest
+    
     steps:
-    - uses: actions/checkout@v3
+    - name: Checkout Code
+      uses: actions/checkout@v2
 
     - name: Set up Go
-      uses: actions/setup-go@v4
+      uses: actions/setup-go@v2
       with:
-        go-version: '1.20'
-
-    - name: Build
-      run: go build -v ./Golang/...
-
-    - name: Test
-      run: go test -v ./Golang/...
+        go-version: '1.20' # Specify your desired Go version
+        
+    - name: Run Go Programs
+      run: |
+        cd Golang
+        for file in *.go; do
+          echo "Checking $file..."
+          go run "$file"
+          if [ $? -eq 0 ]; then
+            echo "$file is working."
+          else
+            echo "Error: $file is not working."
+            exit 1
+          fi
+        done
